version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_cc
    ports:
      - '3000:3000'

    stdin_open: true
    tty: true
  
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_cb
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      PORT: 5000
      DATABASE_URL: 'mongodb://backend:backend@172.100.0.101:27017'

