version: "3"
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: yolo-client
    ports:
     - 3000:80
    depends_on:
      - backend
    stdin_open: true
    tty: true

     
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: yolo-backend
    ports:
      - 5000:5000
  
    environment:
      PORT: 5000
      DATABASE_URL: 'mongodb://backend:backend@172.100.0.101:27017'
    networks:
      backend-net:
        ipv4_address: 172.100.0.100
    depends_on:
      - database
  database:
    container_name: backend_database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    ports:
      - 27017:27017
    networks:
      backend-net:
       ipv4_address: 172.100.0.101
      
networks:
  backend-net:
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
  

